### PR TITLE
Upgrade to php 8

### PR DESCRIPTION
**Pull request by winkbrace**
Not much to say about this PR. It's just an addition of the php version requirements

### CODE REVIEW

**Comment by pelayog** [comment]
Hi! 
Maybe I'm wrong, but I think that `composer.lock` file should be ignored, shouldn't it?

**Comment by winkbrace** [comment]
Whoops, you're right

**Comment by mbiebl** [comment]
Has there been any progress in getting psecio ready for PHP 8.0 (and ideally 8.1 as well)?

**Comment by staabm** [comment]
this PR seems obsolete since https://github.com/psecio/secure_dotenv/commit/b580dea1f40238ea5d353a9668dc0faff0066855

**Comment by winkbrace** [comment]
Great! I'll remove it :)

**Pull request closed without merging**
